// File generated by FlutterFire CLI.
// Manual generation from google-services.json (deliverymovile-c25ff).
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ─────────────────────────────────────────────────────────────────────────
  // ANDROID — configuración correcta (generada desde google-services.json)
  // ─────────────────────────────────────────────────────────────────────────
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM103UYRByhMpYT1k2vTTjGQBEvZrgbdU',
    appId: '1:381626391822:android:63931f9d8e259076ac0b5f',
    messagingSenderId: '381626391822',
    projectId: 'deliverymovile-c25ff',
    storageBucket: 'deliverymovile-c25ff.firebasestorage.app',
  );

  // ─────────────────────────────────────────────────────────────────────────
  // iOS — PENDIENTE de configuración real
  // TODO: Registrar la app iOS en Firebase Console → descargar GoogleService-Info.plist
  //       y reemplazar el appId y apiKey con los valores del plist.
  //       El appId de iOS tiene el formato: 1:381626391822:ios:XXXXXXXXXXXXXXXX
  //       ADVERTENCIA: actualmente usa el appId de Android — Firebase rechazará
  //       las llamadas en iOS en producción.
  // ─────────────────────────────────────────────────────────────────────────
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM103UYRByhMpYT1k2vTTjGQBEvZrgbdU',
    // FIXME: reemplazar con el appId iOS real de Firebase Console
    appId: '1:381626391822:android:63931f9d8e259076ac0b5f',
    messagingSenderId: '381626391822',
    projectId: 'deliverymovile-c25ff',
    storageBucket: 'deliverymovile-c25ff.firebasestorage.app',
    iosBundleId: 'com.cesar.delivery_app',
  );

  // ─────────────────────────────────────────────────────────────────────────
  // macOS — PENDIENTE de configuración real (misma situación que iOS)
  // TODO: igual que iOS — requiere registro en Firebase Console.
  // ─────────────────────────────────────────────────────────────────────────
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM103UYRByhMpYT1k2vTTjGQBEvZrgbdU',
    // FIXME: reemplazar con el appId macOS real de Firebase Console
    appId: '1:381626391822:android:63931f9d8e259076ac0b5f',
    messagingSenderId: '381626391822',
    projectId: 'deliverymovile-c25ff',
    storageBucket: 'deliverymovile-c25ff.firebasestorage.app',
    iosBundleId: 'com.cesar.delivery_app',
  );

  // ─────────────────────────────────────────────────────────────────────────
  // Web — usa el appId de Android (aceptable solo si no se publica como web app)
  // ─────────────────────────────────────────────────────────────────────────
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM103UYRByhMpYT1k2vTTjGQBEvZrgbdU',
    appId: '1:381626391822:android:63931f9d8e259076ac0b5f',
    messagingSenderId: '381626391822',
    projectId: 'deliverymovile-c25ff',
    storageBucket: 'deliverymovile-c25ff.firebasestorage.app',
    authDomain: 'deliverymovile-c25ff.firebaseapp.com',
  );
}
